# Generated by Django 4.1.1 on 2022-10-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Пользователи стендов', 'verbose_name_plural': 'Пользователи стендов'},
        ),
    ]
